// File Overview: AssetPreloader.js
// What this file is: Preloads heavy image/audio assets before gameplay screens.
// When this runs: Loaded when this module is imported by a screen/service.
// Main inputs: React state/props, Firebase data, and shared modules.
// Main outputs: UI rendering and/or side effects (navigation, reads/writes, audio).
// Read this first: Start from the main exported component/function, then follow hooks/callbacks in order.

import { Asset } from 'expo-asset';
import { Image } from 'react-native';

// Shared backgrounds used across many screens
export const BACKGROUND_IMAGES = [
  require('./assets/MenuBackGround/background/bg1.png'),
  require('./assets/MenuBackGround/background/bg2.png'),
  require('./assets/MenuBackGround/background/bg3.png'),
  require('./assets/MenuBackGround/background/bg4.png'),
  require('./assets/MenuBackGround/background/bg5.png'),
  require('./assets/MenuBackGround/background/bg6.png'),
  require('./assets/MenuBackGround/background/bg7.png'),
  require('./assets/MenuBackGround/background/bg8.png'),
  require('./assets/MenuBackGround/background/bg9.png'),
  require('./assets/MenuBackGround/background/bg10.png'),
  require('./assets/MenuBackGround/background/bg11.png'),
  require('./assets/MenuBackGround/background/bg12.png'),
  require('./assets/MenuBackGround/background/bg13.png'),
  require('./assets/MenuBackGround/background/bg132.png'),
  require('./assets/MenuBackGround/background/bg133.png'),
  require('./assets/MenuBackGround/background/bg14.png'),
  require('./assets/MenuBackGround/background/bg15.png'),
  require('./assets/MenuBackGround/background/bg16.png'),
  require('./assets/MenuBackGround/background/bg17.png'),
  require('./assets/MenuBackGround/background/bg18.png'),
  require('./assets/MenuBackGround/background/bg19.png'),
  require('./assets/MenuBackGround/background/bg20.png'),
  require('./assets/MenuBackGround/background/bg21.png'),
  require('./assets/MenuBackGround/background/bg22.png'),
  require('./assets/MenuBackGround/background/bg23.png'),
  require('./assets/MenuBackGround/background/bg24.png'),
  require('./assets/MenuBackGround/background/bg25.png'),
  require('./assets/MenuBackGround/background/bg26.png'),
  require('./assets/MenuBackGround/background/bg27.png'),
  require('./assets/MenuBackGround/background/bg28.png'),
  require('./assets/MenuBackGround/background/bg29.png'),
  require('./assets/MenuBackGround/background/bg30.png'),
  require('./assets/MenuBackGround/background/bg31.png'),
  require('./assets/MenuBackGround/background/bg32.png'),
  require('./assets/MenuBackGround/background/bg33.png'),
  require('./assets/MenuBackGround/background/bg34.png'),
  require('./assets/MenuBackGround/background/bg35.png'),
  require('./assets/MenuBackGround/background/bg36.png'),
  require('./assets/MenuBackGround/background/bg37.png'),
];

// Extra menu backgrounds
export const MENU_BACKGROUNDS = [
  require('./assets/MenuBackGround/background2.png'),
  require('./assets/MenuBackGround/background3.png'),
  require('./assets/MenuBackGround/menubackground.png'),
];

// Game character animation frames
export const CHARACTER_FRAMES = [
  // Chameleon
  require('./assets/charactermovements/chameleon/Idle/Idle1.png'),
  require('./assets/charactermovements/chameleon/Idle/idle2.png'),
  require('./assets/charactermovements/chameleon/walk/walk1.png'),
  require('./assets/charactermovements/chameleon/walk/walk2.png'),
  require('./assets/charactermovements/chameleon/walk/walk3.png'),
  require('./assets/charactermovements/chameleon/punch/punch1.png'),
  require('./assets/charactermovements/chameleon/punch/punch2.png'),
  require('./assets/charactermovements/chameleon/lickattack/LA1.png'),
  require('./assets/charactermovements/chameleon/lickattack/LA2.png'),
  require('./assets/charactermovements/chameleon/lickattack/LA3.png'),
  require('./assets/charactermovements/chameleon/lickattack/LA4.png'),
  require('./assets/charactermovements/chameleon/block/block.png'),
  require('./assets/charactermovements/chameleon/dead/dead1.png'),
  require('./assets/charactermovements/chameleon/dead/dead2.png'),
  require('./assets/charactermovements/chameleon/dead/dead3.png'),
  require('./assets/charactermovements/chameleon/dead/dead4.png'),
  require('./assets/charactermovements/chameleon/dead/dead5.png'),
  require('./assets/charactermovements/chameleon/dead/dead7.png'),
  require('./assets/charactermovements/chameleon/dead/dead8.png'),
  require('./assets/charactermovements/chameleon/dead/dead9.png'),
  require('./assets/charactermovements/chameleon/dead/dead10.png'),
  require('./assets/charactermovements/chameleon/dead/dead11.png'),
  require('./assets/charactermovements/chameleon/dead/dead12.png'),
  require('./assets/charactermovements/chameleon/FINISHHIM/finish1.png'),
  require('./assets/charactermovements/chameleon/FINISHHIM/finish2.png'),
  require('./assets/charactermovements/chameleon/FINISHHIM/finish3.png'),
  // Tiger
  require('./assets/charactermovements/tiger/Idle/idle1.png'),
  require('./assets/charactermovements/tiger/Idle/idle2.png'),
  require('./assets/charactermovements/tiger/Idle/idle3.png'),
  require('./assets/charactermovements/tiger/walk/walk1.png'),
  require('./assets/charactermovements/tiger/walk/walk2.png'),
  require('./assets/charactermovements/tiger/walk/walk3.png'),
  require('./assets/charactermovements/tiger/walk/walk4.png'),
  require('./assets/charactermovements/tiger/walk/walk5.png'),
  require('./assets/charactermovements/tiger/punch/punch1.png'),
  require('./assets/charactermovements/tiger/punch/punch2.png'),
  require('./assets/charactermovements/tiger/punch/punch3.png'),
  require('./assets/charactermovements/tiger/punch/punch4.png'),
  require('./assets/charactermovements/tiger/punch/punch5.png'),
  require('./assets/charactermovements/tiger/scratch/scratch1.png'),
  require('./assets/charactermovements/tiger/scratch/scratch2.png'),
  require('./assets/charactermovements/tiger/scratch/scratch3.png'),
  require('./assets/charactermovements/tiger/scratch/scratch4.png'),
  require('./assets/charactermovements/tiger/block/block2.png'),
  require('./assets/charactermovements/tiger/smash/smash1.png'),
  require('./assets/charactermovements/tiger/smash/smash2.png'),
  require('./assets/charactermovements/tiger/smash/smash3.png'),
  require('./assets/charactermovements/tiger/smash/smash4.png'),
  require('./assets/charactermovements/tiger/smash/smash5.png'),
  require('./assets/charactermovements/tiger/smash/smash6.png'),
  require('./assets/charactermovements/tiger/dead/dead1.png'),
  require('./assets/charactermovements/tiger/dead/dead2.png'),
  require('./assets/charactermovements/tiger/dead/dead3.png'),
  require('./assets/charactermovements/tiger/dead/dead4.png'),
  require('./assets/charactermovements/tiger/dead/dead5.png'),
  require('./assets/charactermovements/tiger/dead/dead6.png'),
  require('./assets/charactermovements/tiger/FinishHim/finish1.png'),
  require('./assets/charactermovements/tiger/FinishHim/finish2.png'),
  require('./assets/charactermovements/tiger/FinishHim/finish3.png'),
  // Cow
  require('./assets/charactermovements/cow/Idle/cowidle1.png'),
  require('./assets/charactermovements/cow/Idle/cowidle2.png'),
  require('./assets/charactermovements/cow/Idle/cowidle3.png'),
  require('./assets/charactermovements/cow/walking/walk1.png'),
  require('./assets/charactermovements/cow/walking/walk2.png'),
  require('./assets/charactermovements/cow/walking/walk3.png'),
  require('./assets/charactermovements/cow/walking/walk4.png'),
  require('./assets/charactermovements/cow/walking/walk5.png'),
  require('./assets/charactermovements/cow/PUNCH/cowpunch1.png'),
  require('./assets/charactermovements/cow/PUNCH/cowpunch2.png'),
  require('./assets/charactermovements/cow/PUNCH/cowpunch3.png'),
  require('./assets/charactermovements/cow/PUNCH/cowpunch4.png'),
  require('./assets/charactermovements/cow/PUNCH/punch5.png'),
  require('./assets/charactermovements/cow/jumpkick/jumpkick1.png'),
  require('./assets/charactermovements/cow/jumpkick/jumpkick2.png'),
  require('./assets/charactermovements/cow/jumpkick/jumpkick3.png'),
  require('./assets/charactermovements/cow/jumpkick/jumpkick4.png'),
  require('./assets/charactermovements/cow/jumpkick/jumpkick5.png'),
  require('./assets/charactermovements/cow/jumpkick/jumpkick6.png'),
  require('./assets/charactermovements/cow/jumpkick/jumpkick7.png'),
  require('./assets/charactermovements/cow/block/block2.png'),
  require('./assets/charactermovements/cow/milk shotting/cowmilkshot1.png'),
  require('./assets/charactermovements/cow/milk shotting/cowmilkshot2.png'),
  require('./assets/charactermovements/cow/milk shotting/cowmilkshot3.png'),
  require('./assets/charactermovements/cow/milk shotting/cowmilkshot4.png'),
  require('./assets/charactermovements/cow/milk shotting/cowmilkshot5.png'),
  require('./assets/charactermovements/cow/milk/milk1.png'),
  require('./assets/charactermovements/cow/milk/milk2.png'),
  require('./assets/charactermovements/cow/milk/milk3.png'),
  require('./assets/charactermovements/cow/milk/milk4.png'),
  require('./assets/charactermovements/cow/milk/milk5.png'),
  require('./assets/charactermovements/cow/milk/milk6.png'),
  require('./assets/charactermovements/cow/cow finished/dead1.png'),
  require('./assets/charactermovements/cow/cow finished/dead2.png'),
  require('./assets/charactermovements/cow/cow finished/dead3.png'),
  require('./assets/charactermovements/cow/FinishHim/finish1.png'),
  require('./assets/charactermovements/cow/FinishHim/finish2.png'),
  require('./assets/charactermovements/cow/FinishHim/finish3.png'),
];

// Character chooser / menu animations
export const MENU_ANIMATIONS = [
  require('./assets/animations/cham0.png'),
  require('./assets/animations/Cham1.png'),
  require('./assets/animations/Cham2.png'),
  require('./assets/animations/Cham3.png'),
  require('./assets/animations/Cham4.png'),
  require('./assets/animations/Cham5.png'),
  require('./assets/animations/Cham6.png'),
  require('./assets/animations/Cham7.png'),
  require('./assets/animations/Cham8.png'),
  require('./assets/animations/Cham9.png'),
  require('./assets/animations/Cham10.png'),
  require('./assets/animations/idle.png'),
  require('./assets/animations/walk1.png'),
  require('./assets/animations/tiger1.png'),
  require('./assets/animations/tiger2.png'),
  require('./assets/animations/tiger3.png'),
  require('./assets/animations/tiger5.png'),
  require('./assets/animations/tiger6.png'),
  require('./assets/animations/tiger7.png'),
  require('./assets/animations/idle1.png'),
  require('./assets/animations/idle2.png'),
  require('./assets/animations/tigerbonus.png'),
  require('./assets/animations/tigerbonus2.png'),
  require('./assets/animations/tigerbonus3.png'),
  require('./assets/animations/cow1.png'),
  require('./assets/animations/cow2.png'),
  require('./assets/animations/cow3.png'),
  require('./assets/animations/cow4.png'),
  require('./assets/animations/cow5.png'),
  require('./assets/animations/cow6.png'),
  require('./assets/animations/cow7.png'),
  require('./assets/animations/cow8.png'),
  require('./assets/animations/cow9.png'),
  require('./assets/animations/cow10.png'),
  require('./assets/animations/cow11.png'),
  require('./assets/animations/cow12.png'),
  require('./assets/animations/cow13.png'),
  require('./assets/animations/cow14.png'),
  require('./assets/animations/cow15.png'),
  require('./assets/animations/cow16.png'),
  require('./assets/animations/cow17.png'),
  require('./assets/animations/cow18.png'),
  require('./assets/animations/cow19.png'),
  require('./assets/animations/cow20.png'),
  require('./assets/animations/cow21.png'),
  require('./assets/animations/cow22.png'),
];

// Background running sprites
export const RUNNING_ANIMATIONS = [
  require('./assets/MenuBackGround/background/bganimations/tigerun1.png'),
  require('./assets/MenuBackGround/background/bganimations/tigerun2.png'),
  require('./assets/MenuBackGround/background/bganimations/tigerun3.png'),
  require('./assets/MenuBackGround/background/bganimations/tigerun4.png'),
  require('./assets/MenuBackGround/background/bganimations/tigerun5.png'),
  require('./assets/MenuBackGround/background/bganimations/sillyrun1.png'),
  require('./assets/MenuBackGround/background/bganimations/sillyrun2.png'),
  require('./assets/MenuBackGround/background/bganimations/sillyrun3.png'),
  require('./assets/MenuBackGround/background/bganimations/sillyrun4.png'),
  require('./assets/MenuBackGround/background/bganimations/sillyrun5.png'),
  require('./assets/MenuBackGround/background/bganimations/sillyrun6.png'),
];

export const ALL_ASSETS = [
  ...BACKGROUND_IMAGES,
  ...MENU_BACKGROUNDS,
  ...CHARACTER_FRAMES,
  ...MENU_ANIMATIONS,
  ...RUNNING_ANIMATIONS,
];

export async function preloadAllAssets() {
  await Asset.loadAsync(ALL_ASSETS);
  // Warm web/native Image cache
  await Promise.all(
    ALL_ASSETS.map(mod => {
      const uri = Asset.fromModule(mod).uri;
      return Image.prefetch(uri).catch(() => null);
    })
  );
}

